# Generated by Django 3.2.4 on 2022-01-31 22:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_company', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('phone_number', models.CharField(max_length=13)),
                ('career_level', models.CharField(choices=[('ST', 'Student'), ('EL', 'Entrylevel'), ('JR', 'Junior'), ('Sr', 'Senior'), ('MGT', 'Management')], max_length=11)),
                ('job_types', models.CharField(choices=[('FT', 'Full time'), ('HT', 'Half time'), ('IN', 'Intership'), ('SB', 'Shift based'), ('WFH', 'Work from home'), ('VN', 'Volunteering')], max_length=20)),
                ('careers_intrests', models.CharField(choices=[('SE', 'Software Engineering'), ('ARCH', 'Architecture'), ('TR', 'Translation'), ('DES', 'Design')], max_length=25)),
                ('min_salary', models.PositiveIntegerField()),
                ('skills', models.CharField(max_length=200)),
                ('birthdate', models.DateTimeField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=15)),
                ('location', models.CharField(max_length=50)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('education_level', models.CharField(choices=[('ST', 'Student'), ('BCH', 'Bachelor'), ('UG', 'UnderGrad'), ('MST', 'Masters'), ('PHD', 'PHD')], max_length=15)),
                ('study_fields', models.CharField(choices=[('Cs', 'Computer Science'), ('ENG', 'Engineering'), ('FA', 'Fine Arts'), ('AS', 'Arts')], max_length=15)),
                ('uni', models.CharField(max_length=200)),
                ('gpa', models.CharField(max_length=2)),
                ('languages', models.CharField(choices=[('DU', 'Deutsch'), ('FR', 'French'), ('En', 'English'), ('AR', 'Arabic')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AccountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(default='****', max_length=4)),
                ('reset_password', models.CharField(blank=True, default='******', max_length=6)),
                ('resend_count', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date2', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date3', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('block', models.BooleanField(blank=True, default=False)),
                ('freeze', models.BooleanField(blank=True, default=False)),
                ('foul_count', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
