# Generated by Django 3.2.4 on 2021-12-16 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('phone_number', models.CharField(max_length=13)),
                ('career_level', models.CharField(choices=[('ST', 'Student'), ('EL', 'Entrylevel'), ('JR', 'Junior'), ('Sr', 'Senior'), ('MGT', 'Management')], max_length=11)),
                ('job_types', models.CharField(choices=[('FT', 'Full time'), ('HT', 'Half time'), ('IN', 'Intership'), ('SB', 'Shift based'), ('WFH', 'Work from home'), ('VN', 'Volunteering')], max_length=20)),
                ('careers_intrests', models.CharField(choices=[('SE', 'Software Engineering'), ('ARCH', 'Architecture'), ('TR', 'Translation'), ('DES', 'Design')], max_length=25)),
                ('min_salary', models.PositiveIntegerField()),
                ('skills', models.CharField(max_length=200)),
                ('birthdate', models.DateTimeField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15)),
                ('Location', models.CharField(max_length=50)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('education_level', models.CharField(choices=[('ST', 'Student'), ('BCH', 'Bachelor'), ('UG', 'UnderGrad'), ('MST', 'Masters'), ('PHD', 'PHD')], max_length=15)),
                ('study_fields', models.CharField(choices=[('Cs', 'Computer Science'), ('ENG', 'Engineering'), ('FA', 'Fine Arts'), ('AS', 'Arts')], max_length=15)),
                ('uni', models.CharField(max_length=200)),
                ('gpa', models.CharField(max_length=2)),
                ('languages', models.CharField(choices=[('DU', 'Deutsch'), ('FR', 'French'), ('En', 'English'), ('AR', 'Arabic')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='firstname',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='lastname',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
