# Generated by Django 3.2.4 on 2021-12-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211216_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
