# Generated by Django 3.2.4 on 2022-03-16 16:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='file',
        ),
        migrations.AddField(
            model_name='account',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
