# Generated by Django 3.2.4 on 2022-01-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
