# Generated by Django 3.2.4 on 2022-03-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220316_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_types',
            field=models.CharField(choices=[('FT', 'Full time'), ('HT', 'Half time'), ('IN', 'Intership'), ('SB', 'Shift based'), ('WFH', 'Work from home'), ('VN', 'Volunteering')], max_length=20, null=True),
        ),
    ]
