# Generated by Django 3.2.4 on 2022-02-06 16:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_is_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='firstname',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastname',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='AccountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(default='****', max_length=4)),
                ('reset_password', models.CharField(blank=True, default='******', max_length=6)),
                ('resend_count', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date2', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date3', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('block', models.BooleanField(blank=True, default=False)),
                ('freeze', models.BooleanField(blank=True, default=False)),
                ('foul_count', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
