# Generated by Django 3.2.4 on 2022-03-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_job_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_types',
            field=models.CharField(choices=[('FT', 'Full time'), ('HT', 'Half time'), ('IN', 'Intership'), ('SB', 'Shift based'), ('WFH', 'Work from home'), ('VN', 'Volunteering')], default='FT', max_length=20),
        ),
    ]
