<<<<<<< HEAD
# Generated by Django 3.2.4 on 2022-03-30 16:45
=======
# Generated by Django 3.2.4 on 2022-03-30 17:20
>>>>>>> 6e278adec54b462866dce590dff6e24f25feeee8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_job_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
