# Generated by Django 3.2.4 on 2022-02-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_accountcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='company_name',
        ),
        migrations.AddField(
            model_name='accountcode',
            name='verification_code',
            field=models.CharField(default='****', max_length=4),
        ),
    ]
