# Generated by Django 3.2.2 on 2022-04-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='specialities',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career_level',
            field=models.CharField(default='JR', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='careers_intrests',
            field=models.CharField(default='SE', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_level',
            field=models.CharField(default='BCH', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_types',
            field=models.CharField(default='FT', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.CharField(default='En', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_fields',
            field=models.CharField(default='ENG', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uni',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
