# Generated by Django 3.2.4 on 2022-03-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20220206_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='account',
            name='firstname',
            field=models.CharField(default='firstname', max_length=25),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastname',
            field=models.CharField(default='lastname', max_length=25),
        ),
        migrations.AlterField(
            model_name='accountcode',
            name='reset_password',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='accountcode',
            name='verification_code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career_level',
            field=models.CharField(choices=[('ST', 'Student'), ('EL', 'Entrylevel'), ('JR', 'Junior'), ('Sr', 'Senior'), ('MGT', 'Management')], default='JR', max_length=11),
        ),
        migrations.AlterField(
            model_name='profile',
            name='careers_intrests',
            field=models.CharField(choices=[('SE', 'Software Engineering'), ('ARCH', 'Architecture'), ('TR', 'Translation'), ('DES', 'Design')], default='SE', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education_level',
            field=models.CharField(choices=[('ST', 'Student'), ('BCH', 'Bachelor'), ('UG', 'UnderGrad'), ('MST', 'Masters'), ('PHD', 'PHD')], default='BCH', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gpa',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.CharField(choices=[('DU', 'Deutsch'), ('FR', 'French'), ('En', 'English'), ('AR', 'Arabic')], default='En', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_salary',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_fields',
            field=models.CharField(choices=[('Cs', 'Computer Science'), ('ENG', 'Engineering'), ('FA', 'Fine Arts'), ('AS', 'Arts')], default='ENG', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uni',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='years_of_experience',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
