# Generated by Django 3.2.4 on 2022-03-30 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_alter_profile_job_types'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('requirements', models.CharField(max_length=1000)),
                ('education_level', models.CharField(choices=[('ST', 'Student'), ('BCH', 'Bachelor'), ('UG', 'UnderGrad'), ('MST', 'Masters'), ('PHD', 'PHD')], default='BCH', max_length=15)),
                ('experience', models.CharField(max_length=2)),
                ('salary', models.CharField(max_length=10)),
                ('isConfidential', models.BooleanField(default=True)),
                ('applicants', models.ManyToManyField(to='account.Profile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyprofile')),
            ],
        ),
    ]
