# Generated by Django 3.2.2 on 2022-05-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20220424_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_title',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
