# Generated by Django 3.2.4 on 2022-04-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='applicantscount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
