# Generated by Django 3.2.4 on 2022-04-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobs_applicantscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='career_level',
            field=models.CharField(default='Junior', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='education_level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
