# Generated by Django 3.2.2 on 2022-05-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20220508_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_title',
            field=models.CharField(default='junior', max_length=100),
        ),
    ]
