# Generated by Django 3.2.4 on 2022-03-06 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('logo', models.BinaryField(editable=True, null=True)),
                ('content_type', models.CharField(help_text='The MIMEType of the file', max_length=256, null=True)),
                ('size_of_company', models.CharField(choices=[('SB', 'Small Business'), ('ME', 'Mid Market enterprise'), ('EN', 'Enterprise')], default='SB', max_length=25)),
                ('company_name', models.CharField(max_length=25, null=True)),
                ('company_info', models.CharField(max_length=1500, null=True)),
                ('company_industries', models.CharField(choices=[('T', 'Tech'), ('ARCH', 'Architecture'), ('TR', 'Translation'), ('DES', 'Design'), ('MA', 'Media and Advertising'), ('ME', 'Medicine')], default='T', max_length=25)),
                ('company_type', models.CharField(choices=[('PRV', 'Private company'), ('PUB', 'Public Company'), ('NPO', 'Non Profit Organization')], default='PRV', max_length=25)),
                ('mobile_number', models.CharField(max_length=13, null=True)),
                ('job_title', models.CharField(max_length=25, null=True)),
                ('no_of_employees', models.CharField(max_length=9, null=True)),
                ('isInternational', models.BooleanField(null=True)),
                ('headquarters', models.CharField(max_length=30, null=True)),
                ('founded_at', models.DateTimeField(null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
