# Generated by Django 3.2.4 on 2022-01-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_account_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('logo', models.BinaryField(editable=True, null=True)),
                ('content_type', models.CharField(help_text='The MIMEType of the file', max_length=256, null=True)),
                ('size_of_company', models.CharField(choices=[('SB', 'Small Business'), ('ME', 'Mid Market enterprise'), ('EN', 'Enterprise')], max_length=25)),
                ('company_industries', models.CharField(choices=[('T', 'Tech'), ('ARCH', 'Architecture'), ('TR', 'Translation'), ('DES', 'Design'), ('MA', 'Media and Advertising'), ('ME', 'Medicine')], max_length=25)),
                ('company_type', models.CharField(choices=[('PRV', 'Private company'), ('PUB', 'Public Company'), ('NPO', 'Non Profit Organization')], max_length=25)),
                ('no_of_employees', models.CharField(max_length=9)),
                ('isInternational', models.BooleanField()),
                ('headquarters', models.CharField(max_length=30)),
                ('founded_at', models.DateTimeField()),
            ],
        ),
    ]
