# Generated by Django 3.2.4 on 2022-02-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='job_title',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
