# Generated by Django 3.2.4 on 2022-02-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyprofile_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='mobile_number',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
