# Generated by Django 3.2.4 on 2022-04-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(default='', max_length=25),
        ),
    ]
