# Generated by Django 3.2.4 on 2022-02-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companyprofile_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='company',
            new_name='company_name',
        ),
    ]
