# Generated by Django 3.2.2 on 2022-04-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_review_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='logo',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_industries',
            field=models.CharField(default='T', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_type',
            field=models.CharField(default='PRV', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='size_of_company',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
