# Generated by Django 3.2.4 on 2022-04-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_review_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_industries',
            field=models.CharField(default='T', max_length=25),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_type',
            field=models.CharField(default='PRV', max_length=25),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='size_of_company',
            field=models.CharField(default='SB', max_length=25),
        ),
    ]
