# Generated by Django 3.2.4 on 2022-02-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20220206_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_industries',
            field=models.CharField(choices=[('T', 'Tech'), ('ARCH', 'Architecture'), ('TR', 'Translation'), ('DES', 'Design'), ('MA', 'Media and Advertising'), ('ME', 'Medicine')], default='T', max_length=25),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_type',
            field=models.CharField(choices=[('PRV', 'Private company'), ('PUB', 'Public Company'), ('NPO', 'Non Profit Organization')], default='PRV', max_length=25),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='founded_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='headquarters',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='isInternational',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='no_of_employees',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='size_of_company',
            field=models.CharField(choices=[('SB', 'Small Business'), ('ME', 'Mid Market enterprise'), ('EN', 'Enterprise')], default='SB', max_length=25),
        ),
    ]
