# Generated by Django 3.2.4 on 2022-04-21 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20220419_0637'),
        ('companies', '0005_auto_20220420_2340'),
    ]

    operations = [
    ]
