# Generated by Django 3.2.2 on 2022-05-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20220424_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='specialities',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
