# Generated by Django 3.2.4 on 2022-04-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_merge_0005_auto_20220419_0637_0005_auto_20220420_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='logo',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_industries',
            field=models.CharField(default='T', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_type',
            field=models.CharField(default='PRV', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='size_of_company',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
