# Generated by Django 3.2.4 on 2022-03-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20220206_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_info',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
